allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - expo-blur@56.0.4

overrides:
  lightningcss: 1.30.1
  "@types/react": 19.2.17

patchedDependencies:
  expo-share-extension@5.0.6: patches/expo-share-extension@5.0.6.patch
  expo-share-intent@7.0.0: patches/expo-share-intent@7.0.0.patch
  react-native-css: patches/react-native-css.patch
